import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-[20px] md:p-[70px] lg:p-[100px] bg-black/95 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
